services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck: # detect when the DB is actually ready :D
      test: ["CMD-SHELL", "pg_isready -d ${PG_DB} -U ${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DB}
    depends_on:
      - db:
          condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
